"""initial migration with companies branches and users

Revision ID: 5a70a033e2c4
Revises: 
Create Date: 2026-02-05 01:51:27.879310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a70a033e2c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Drop existing foreign keys
    op.drop_constraint('branches_ibfk_1', 'branches', type_='foreignkey')
    
    # Step 2: Alter column types
    op.alter_column('companies', 'id',
               existing_type=mysql.CHAR(length=32),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('branches', 'id',
               existing_type=mysql.CHAR(length=32),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('branches', 'company_id',
               existing_type=mysql.CHAR(length=32),
               type_=sa.BigInteger(),
               existing_nullable=False)
    
    # Step 3: Recreate foreign key
    op.create_foreign_key('branches_ibfk_1', 'branches', 'companies', ['company_id'], ['id'])
    
    # Step 4: Create users table with foreign keys
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'EMPLOYEE', name='user_role'), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Drop users table
    op.drop_table('users')
    
    # Step 2: Drop the recreated foreign key
    op.drop_constraint('branches_ibfk_1', 'branches', type_='foreignkey')
    
    # Step 3: Revert column types
    op.alter_column('branches', 'company_id',
               existing_type=sa.BigInteger(),
               type_=mysql.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('branches', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('companies', 'id',
               existing_type=sa.BigInteger(),
               type_=mysql.CHAR(length=32),
               existing_nullable=False,
               autoincrement=True)
    
    # Step 4: Recreate original foreign key
    op.create_foreign_key('branches_ibfk_1', 'branches', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
